import type { ProductSeedItem } from './types';

/** Sample menu for restaurant-v1 storefronts (prices in INR). */
export function restaurantCatalogItems(): ProductSeedItem[] {
  return [
    {
      name: "Aruna's Signature Chicken Biryani",
      brand: 'Slow-cooked · Dum style',
      priceInr: 320,
      imageUrl: '',
      category: 'Biryani',
      isAccessory: false,
      dietType: 'non-veg',
      featuredGroup: 'trending',
      featuredSort: 0,
    },
    {
      name: 'Andhra Chicken Curry',
      brand: 'Fiery · House spice blend',
      priceInr: 260,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'non-veg',
      featuredGroup: 'trending',
      featuredSort: 1,
    },
    {
      name: 'Tandoori Chicken (Full)',
      brand: 'Charcoal grilled',
      priceInr: 380,
      imageUrl: '',
      category: 'Tandoor',
      isAccessory: false,
      dietType: 'non-veg',
      featuredGroup: 'trending',
      featuredSort: 2,
    },
    {
      name: 'Mutton Rogan Josh',
      brand: 'Slow braised',
      priceInr: 420,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'non-veg',
      featuredGroup: 'trending',
      featuredSort: 3,
    },
    {
      name: 'Chilli Garlic Prawns',
      brand: 'Coastal special',
      priceInr: 340,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: "Eagle's Family Thali",
      brand: "Serves 4 · Chef's selection",
      priceInr: 1150,
      imageUrl: '',
      category: 'Thali',
      isAccessory: false,
      dietType: 'non-veg',
      featuredGroup: 'deal',
      featuredSort: 0,
    },
    {
      name: 'Guntur Chicken Fry',
      brand: 'Crispy · Spicy',
      priceInr: 280,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Apollo Fish',
      brand: 'Tangy · Crispy batter',
      priceInr: 320,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Chicken 65',
      brand: 'Deep fried · Andhra style',
      priceInr: 260,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Mutton Pepper Fry',
      brand: 'Black pepper · Slow roasted',
      priceInr: 360,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Crab Masala Fry',
      brand: 'Coastal spice mix',
      priceInr: 390,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Egg Bhurji',
      brand: 'Soft scramble · Masala',
      priceInr: 140,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Veg Manchurian Dry',
      brand: 'Indo-Chinese · Crispy',
      priceInr: 220,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'veg',
    },
    {
      name: 'Chicken Lollipop',
      brand: 'Spicy glaze · Crunchy',
      priceInr: 270,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Pepper Chicken Dry',
      brand: 'Chettinad pepper masala',
      priceInr: 290,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Paneer Butter Masala',
      brand: 'Creamy tomato gravy',
      priceInr: 240,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'veg',
    },
    {
      name: 'Butter Chicken',
      brand: 'Mild · Tomato butter gravy',
      priceInr: 280,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Fish Pulusu',
      brand: 'Tamarind · Andhra sour curry',
      priceInr: 300,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Gongura Mutton',
      brand: 'Sorrel leaves · Tangy',
      priceInr: 440,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Natu Kodi Pulusu',
      brand: 'Country chicken · Home style',
      priceInr: 320,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Dal Fry',
      brand: 'Tempered · Comfort bowl',
      priceInr: 160,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'veg',
    },
    {
      name: 'Mixed Veg Curry',
      brand: 'Seasonal vegetables',
      priceInr: 200,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'veg',
    },
    {
      name: 'Prawn Curry',
      brand: 'Coastal coconut gravy',
      priceInr: 360,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      dietType: 'non-veg',
    },
    {
      name: 'Fresh Lime Soda',
      brand: 'Chilled · House made',
      priceInr: 60,
      imageUrl: '',
      category: 'Beverages',
      isAccessory: false,
      dietType: 'veg',
    },
  ];
}
