import type { ProductSeedItem } from './types';

/** Sample menu for restaurant-v1 storefronts (prices in INR). */
export function restaurantCatalogItems(): ProductSeedItem[] {
  return [
    {
      name: "Aruna's Signature Chicken Biryani",
      brand: 'Slow-cooked · Dum style',
      priceInr: 320,
      imageUrl: '',
      category: 'Biryani',
      isAccessory: false,
      featuredGroup: 'trending',
      featuredSort: 0,
    },
    {
      name: 'Andhra Chicken Curry',
      brand: 'Fiery · House spice blend',
      priceInr: 260,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      featuredGroup: 'trending',
      featuredSort: 1,
    },
    {
      name: 'Tandoori Chicken (Full)',
      brand: 'Charcoal grilled',
      priceInr: 380,
      imageUrl: '',
      category: 'Tandoor',
      isAccessory: false,
      featuredGroup: 'trending',
      featuredSort: 2,
    },
    {
      name: 'Mutton Rogan Josh',
      brand: 'Slow braised',
      priceInr: 420,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
      featuredGroup: 'trending',
      featuredSort: 3,
    },
    {
      name: 'Chilli Garlic Prawns',
      brand: 'Coastal special',
      priceInr: 340,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
    },
    {
      name: "Eagle's Family Thali",
      brand: "Serves 4 · Chef's selection",
      priceInr: 1150,
      imageUrl: '',
      category: 'Thali',
      isAccessory: false,
      featuredGroup: 'deal',
      featuredSort: 0,
    },
    {
      name: 'Guntur Chicken Fry',
      brand: 'Crispy · Spicy',
      priceInr: 280,
      imageUrl: '',
      category: 'Starters',
      isAccessory: false,
    },
    {
      name: 'Paneer Butter Masala',
      brand: 'Creamy tomato gravy',
      priceInr: 240,
      imageUrl: '',
      category: 'Curries',
      isAccessory: false,
    },
    {
      name: 'Fresh Lime Soda',
      brand: 'Chilled · House made',
      priceInr: 60,
      imageUrl: '',
      category: 'Beverages',
      isAccessory: false,
    },
  ];
}
